kind: pipeline
type: docker
name: charlotte

steps:
  - name: build
    image: golang:1.9
    commands:
      - pwd
      - go env
      - go version
      - go build

  - name: publish
    image: plugins/docker
    repo: dogfood/charlotte

trigger:
  event:
    - push

