kind: pipeline
type: docker
name: charlotte

steps:
  - name: build
    image: golang:latest
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    commands:
      - CGO_ENABLED=0 go build -o demo-app

  - name: docker
    image: plugins/docker
    settings:
      repo: ztt/drone-demo

trigger:
  event:
    - push

